#ifndef _CC_COMMANDS_HPP_
#define _CC_COMMANDS_HPP_


#define FETCH_GLOBAL_IMAGE 1
#define FETCH_NODES_POS 2
#define UPDATE_MAP_NUMBER 3
#define UPDATE_GLOBAL_AREA_POLYGON 4
#define FETCH_MAP_NUMBER 5
#define FETCH_GLOBAL_POLYGON 6

#endif